### ISSUE TITLE
Multiple Windows Webview2 component crash

### ISSUE THREAD

**Issue by officesolutions-it** [microsoft/WinUI-Gallery#1032]
### Which version of the app?

WinUI 3 Gallery

### Description

Closing a new window when a webview2 component is loaded causes the application to crash.

If you go to Windows -> Create Multiple windows, then on the second window that opens, navigate to the WebView2 component,  then attempt to close this window, this will cause a crash.

### Windows version

November 2021 Update/21H2 (19044)

**Comment by officesolutions-it** [comment]
This is a separate issue, the one in #964 relates to the window not closing.
This issue is the app crashes when attempting to close a WebView2 window.

**Comment by gabbybilka** [comment]
Fixed in Windows App SDK 1.1.2, see [release notes](https://aka.ms/windowsappsdk/1.1/1.1.2/release-notes) for more info.

**Comment by krschau** [comment]
I think @officesolutions-it is right, this is a different issue. Re-opening. This was not fixed in 1.1.2.

**Comment by DmitriyKomin** [comment]
Looks like duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/6872.

@officesolutions-it  - can you try the workaround listed in that issue?

**Comment by karkarl** [comment]
Closing - duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/6872 , fixed in Windows App SDK 1.3.1 (1.3.230502000).
